# theme: jekyll-theme-minimal
remote_theme: samarsault/plainwhite-jekyll
plainwhite:
  name: Chris Sidebotham
  tagline: Cloud Adoption. M365 Advocate
  date_format: "%b %-d, %Y"
  
  social_links: 
    linkedIn: in/chrissidebotham 
  sitemap: false 
  dark_mode: true
  search: true
  bareurl: "/"
  
