title: Chris Sidebotham
email: Chris@blackfishonline.co.uk
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
show_excerpts: false

# theme: jekyll-theme-minimal
remote_theme: samarsault/plainwhite-jekyll
plugins: 
  - jekyll-feed
  
plainwhite:
  name: Chris Sidebotham
  tagline: Cloud Adoption. M365 Advocate
  date_format: "%b %-d, %Y"
  
  social_links: 
    linkedIn: in/chrissidebotham 
  sitemap: false 
  dark_mode: true
  search: true
  bareurl: "/"
  
