title: Chris Sidebotham
email: Chris@blackfishonline.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Blog Site for Chris Sidebotham - Professional Services Engingeer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blackfishonline.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ChrisSidebotham
show_excerpts: true

# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll
theme: plainwhite

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

plainwhite: 
  name: Chris Sidebotham
  tagline: Professional Services Engineer
  portfolio_image:  "assets/Memoji-v2.png" # the path from the directory of the site to the image to display (no / at the start)
  date_format: "%b %-d, %Y"
  dark_mode: true
  search: true
  sitemap: true
  html_lang: "en-GB"
  discus_shortname: blackfishonline

  condensed_mobile:
    - home
    - post
    - page

  social_links: 
    github: ChrisSidebotham
    linkedIn: in/ChrisSidebotham
    rss: rss
    gitlab: ChrisSidebotham
  
  navigation: 
    - title: Home
      url: "/"    
    - title: About Me
      url: "/bio"